-- =============================================================
-- FILE: 076_custom_pages.sql  (GÜNCEL • Drizzle şemayla birebir)
-- =============================================================

DROP TABLE IF EXISTS `custom_pages`;

CREATE TABLE `custom_pages` (
  `id`               CHAR(36)      NOT NULL,
  `title`            VARCHAR(255)  NOT NULL,
  `slug`             VARCHAR(255)  NOT NULL,

  -- JSON-string: {"html":"..."}
  `content`          LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL
                     CHECK (JSON_VALID(`content`)),

  -- ✅ Storage pattern (şema ile aynı adlar)
  `image_url`         VARCHAR(500) DEFAULT NULL,
  `storage_asset_id`  CHAR(36)     DEFAULT NULL,
  `alt`               VARCHAR(255) DEFAULT NULL,

  `meta_title`       VARCHAR(255)  DEFAULT NULL,
  `meta_description` VARCHAR(500)  DEFAULT NULL,
  `is_published`     TINYINT(1)    NOT NULL DEFAULT 0,

  `created_at`       DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`       DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_custom_pages_slug`          (`slug`),
  KEY        `custom_pages_created_idx`      (`created_at`),
  KEY        `custom_pages_updated_idx`      (`updated_at`),
  KEY        `custom_pages_is_published_idx` (`is_published`),
  KEY        `custom_pages_asset_idx`        (`storage_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- SEED (örnek sayfalar) – storage alanları opsiyonel, NULL geçiyoruz
-- =============================================================

INSERT INTO `custom_pages`
(`id`, `title`, `slug`, `content`,
 `image_url`, `storage_asset_id`, `alt`,
 `meta_title`, `meta_description`, `is_published`, `created_at`, `updated_at`)
VALUES
-- HAKKIMIZDA
(
  UUID(),
  'Hakkımızda',
  'hakkimizda',
  JSON_OBJECT('html', 
    CONCAT(
      '<p><strong>İstanbul\'un en deneyimli mezar yapım firması</strong> olarak <strong>25 yılı aşkın süredir mezar inşaatı, mezar taşı yapımı, mermer mezar modelleri ve mezar bakım hizmetleri</strong> sunmaktayız. <em>Kaliteli malzeme, uygun fiyat</em> ve <em>profesyonel işçilik</em> garantisi ile sektörde güvenilir bir isim haline geldik.</p>',
      '<p><strong>Mezar yapımı konusunda uzman ekibimiz</strong>, tek kişilik mezar, iki kişilik mezar, aile mezarı ve özel tasarım mezar modelleri olmak üzere <em>her türlü mezar yapım işlerini</em> gerçekleştirmektedir. <strong>Granit mezar taşı, mermer mezar taşı, traverten mezar</strong> ve modern mezar tasarımları ile sevdiklerinizin anısını en güzel şekilde yaşatıyoruz.</p>',
      '<p><strong>İstanbul\'daki tüm mezarlıklarda hizmet veren firmamız</strong> - Karaca Ahmet, Zincirlikuyu, Eyüp Sultan, Edirnekapı, Kilyos, Şile mezarlıkları başta olmak üzere - <em>İstanbul Büyükşehir Belediyesi standartlarına uygun</em> mezar yapımı yapmaktadır. <strong>Mezar fiyatları</strong> konusunda şeffaf ve uygun fiyat politikamız ile müşteri memnuniyetini önceliğimiz haline getirdik.</p>',
      '<p><strong>Mezar onarımı, mezar restorasyonu, mezar çiçeklendirme</strong> ve <strong>mezar toprak doldurumu</strong> hizmetlerimizle kapsamlı çözümler sunuyoruz. Modern teknoloji ve geleneksel el işçiliğini birleştirerek <em>dayanıklı ve estetik mezar yapımı</em> garantisi veriyoruz. <strong>Ücretsiz keşif, proje çizimi ve fiyat teklifi</strong> ile müşterilerimize en iyi hizmeti sunmaya devam ediyoruz.</p>',
      '<p><strong>7/24 mezar yapım hizmeti</strong> veren firmamız, acil durumlarda bile <em>hızlı ve kaliteli çözümler</em> üretmektedir. <strong>Garantili mezar yapımı, uygun taksit imkânları</strong> ve <strong>ücretsiz nakliye hizmeti</strong> ile İstanbul\'da mezar yapımı konusunda en güvenilir adres olmayı sürdürüyoruz.</p>'
    )
  ),
  'https://res.cloudinary.com/dbozv7wqd/image/upload/v1762878680/custom_pages/609da17f-bee8-11f0-947f-e7685059cf04/cover/mezartasi.png', NULL, NULL,
  'Hakkımızda - Mezarisim.com | İstanbul\'un En Deneyimli Mezar Yapım Firması',
  '25 yıllık deneyimimizle İstanbul\'da mezar yapımı, mezar taşı, mermer ve granit mezar modelleri. Kaliteli malzeme, uygun fiyat, profesyonel işçilik garantisi.',
  1,
  NOW(3), NOW(3)
),
-- MİSYON & VİZYON
(
  UUID(),
  'Misyonumuz - Vizyonumuz',
  'misyon-vizyon',
  JSON_OBJECT('html',
    CONCAT(
      '<section class="container mx-auto px-4 py-8">',
        '<h1 class="text-3xl md:text-4xl font-bold text-teal-600 mb-4">MİSYONUMUZ - VİZYONUMUZ</h1>',
        '<p class="text-gray-700 mb-8">İstanbul\'da mezar yapımı konusunda 25 yıllık deneyimimizle, sevdiklerinizin anısını ebedileştirme misyonu taşıyoruz.</p>',
        '<div class="grid grid-cols-1 gap-8">',
          '<div class="bg-gradient-to-br from-teal-50 to-teal-100 p-6 rounded-xl shadow">',
            '<div class="flex items-center mb-4">',
              '<div class="w-10 h-10 bg-teal-500 rounded-full text-white flex items-center justify-center mr-3">🎯</div>',
              '<h2 class="text-2xl text-teal-700 m-0">Misyonumuz</h2>',
            '</div>',
            '<div class="space-y-4 text-gray-700">',
              '<p><strong>İstanbul\'da mezar yapımı sektöründe</strong> müşteri memnuniyetini en üst seviyede tutarak, <em>kaliteli mezar inşaatı, mezar taşı yapımı ve mezar bakım hizmetleri</em> sunmak temel misyonumuzdur. <strong>Mermer mezar, granit mezar taşı, traverten mezar</strong> ve modern mezar tasarımları ile sevdiklerinizin anısını en değerli şekilde yaşatıyoruz.</p>',
              '<p><strong>Uygun fiyat, yüksek kalite ve profesyonel işçilik</strong> ilkeleriyle hareket ederek, <em>tek kişilik mezar, iki kişilik mezar, aile mezarı</em> ve özel tasarım mezar projelerinde <strong>İstanbul Büyükşehir Belediyesi standartlarına uygun</strong> çalışmalar gerçekleştiriyoruz. Her mezar yapımında <em>dayanıklılık, estetik ve mükemmellik</em> hedefliyoruz.</p>',
              '<p><strong>7/24 mezar yapım hizmeti, ücretsiz keşif, garantili işçilik</strong> ve müşteri odaklı yaklaşımımızla İstanbul\'daki tüm mezarlıklarda - <em>Karaca Ahmet, Zincirlikuyu, Eyüp Sultan, Edirnekapı</em> - güvenilir çözümler üretmek amacımızdır.</p>',
            '</div>',
          '</div>',
          '<div class="bg-gradient-to-br from-blue-50 to-blue-100 p-6 rounded-xl shadow">',
            '<div class="flex items-center mb-4">',
              '<div class="w-10 h-10 bg-blue-500 rounded-full text-white flex items-center justify-center mr-3">🌟</div>',
              '<h2 class="text-2xl text-blue-700 m-0">Vizyonumuz</h2>',
            '</div>',
            '<div class="space-y-4 text-gray-700">',
              '<p><strong>2030 yılına kadar İstanbul\'da mezar yapımı konusunda lider firma</strong> olmak ve <em>Türkiye genelinde en güvenilir mezar inşaat şirketi</em> unvanını kazanmak vizyonumuzdur. <strong>Modern teknoloji, geleneksel el işçiliği ve yenilikçi tasarım</strong> anlayışını birleştirerek sektörde çığır açan projeler hayata geçirmeyi hedefliyoruz.</p>',
              '<p><strong>Çevre dostu mezar yapımı, sürdürülebilir malzeme kullanımı</strong> ve <em>dijital mezar takip sistemi</em> ile gelecek nesillere örnek olacak bir hizmet modeli oluşturmayı amaçlıyoruz. <strong>Mezar fiyatlarında şeffaflık, ödeme kolaylığı</strong> ve <em>müşteri memnuniyet garantisi</em> ile sektörde yeni standartlar belirlemeyi hedefliyoruz.</p>',
              '<p><strong>Mezar onarımı, mezar restorasyonu, mezar çiçeklendirme</strong> ve <strong>mezar toprak doldurumu</strong> alanlarında da uzmanlaşarak, <em>komple mezar hizmet çözümleri</em> sunan tek adres olmayı vizyonumuz olarak benimsedik. <strong>Kalite, güven ve mükemmellik</strong> değerlerimizle İstanbul\'da mezar yapımının vazgeçilmez markası olmayı sürdüreceğiz.</p>',
            '</div>',
          '</div>',
          '<div class="grid sm:grid-cols-2 gap-4">',
            '<div class="bg-white border-l-4 border-teal-500 p-4 rounded-r-lg shadow">',
              '<h3 class="text-teal-600 font-semibold mb-2">🏗️ Mezar Yapım Uzmanlığımız</h3>',
              '<ul class="text-sm text-gray-700 space-y-1">',
                '<li>• <strong>25+ yıl</strong> mezar inşaat deneyimi</li>',
                '<li>• <strong>1000+ başarılı</strong> mezar projesi</li>',
                '<li>• <strong>İBB onaylı</strong> tüm mezarlıklarda hizmet</li>',
                '<li>• <strong>7/24</strong> acil mezar yapım hizmeti</li>',
              '</ul>',
            '</div>',
            '<div class="bg-white border-l-4 border-blue-500 p-4 rounded-r-lg shadow">',
              '<h3 class="text-blue-600 font-semibold mb-2">💎 Kalite Garantilerimiz</h3>',
              '<ul class="text-sm text-gray-700 space-y-1">',
                '<li>• <strong>A+ kalite</strong> mermer ve granit</li>',
                '<li>• <strong>5 yıl garanti</strong> tüm işçilik</li>',
                '<li>• <strong>Ücretsiz keşif</strong> ve proje çizimi</li>',
                '<li>• <strong>Uygun taksit</strong> imkânları</li>',
              '</ul>',
            '</div>',
          '</div>',
        '</div>',
      '</section>'
    )
  ),
  'https://res.cloudinary.com/dbozv7wqd/image/upload/v1762878680/custom_pages/609da17f-bee8-11f0-947f-e7685059cf04/cover/mezartasi.png', NULL, NULL,
  'Misyonumuz ve Vizyonumuz - Mezarisim.com | İstanbul Mezar Yapımı',
  '25 yıllık deneyimimizle misyonumuz ve 2030 vizyonumuz: kalite, güven, sürdürülebilirlik ve 7/24 hizmet.',
  1,
  NOW(3), NOW(3)
),
-- KALİTE POLİTİKAMIZ
(
  UUID(),
  'Kalite Politikamız',
  'kalite-politikamiz',
  JSON_OBJECT('html',
    CONCAT(
      '<section class="container mx-auto px-4 py-8">',
        '<h1 class="text-3xl md:text-4xl font-bold text-teal-600 mb-4">KALİTE POLİTİKAMIZ</h1>',
        '<p class="text-gray-700 mb-8"><strong>İstanbul\'da mezar yapımı sektöründe kalite lideri</strong> olarak, <em>25 yıllık deneyimimizle</em> müşterilerimize <strong>A+ kalite garantisi</strong> sunuyoruz.</p>',
        '<div class="bg-gradient-to-br from-teal-50 to-blue-50 p-8 rounded-xl border-l-4 border-teal-500 shadow-lg mb-8">',
          '<h2 class="text-2xl text-teal-600 mb-6 flex items-center">',
            '<span class="w-10 h-10 bg-teal-500 rounded-full flex items-center justify-center mr-4 text-white">🏆</span>',
            'Mezar Yapımında Kalite Anlayışımız',
          '</h2>',
          '<div class="space-y-5 text-gray-700">',
            '<p><strong>İstanbul\'da mezar yapımı konusunda sektörün en güvenilir firması</strong> olarak, <em>kaliteli mezar inşaatı, mermer mezar taşı yapımı, granit mezar taşı üretimi</em> ve <strong>mezar bakım hizmetlerinde</strong> asla taviz vermediğimiz standartlarımız bulunmaktadır. <strong>Tek kişilik mezar, iki kişilik mezar, aile mezarı</strong> projelerinde <em>İstanbul Büyükşehir Belediyesi normlarına uygun</em> kaliteli işçilik garantisi veriyoruz.</p>',
            '<p><strong>Mezar yapım kalitemiz</strong>, kullandığımız <em>A+ sınıf mermer, granit, traverten</em> malzemelerden başlayarak, <strong>profesyonel mezar ustalarımızın</strong> deneyimi ile devam eder. <em>Mezar onarımı, mezar restorasyonu, mezar çiçeklendirme</em> ve <strong>mezar toprak doldurumu</strong> hizmetlerimizde de aynı kalite standardını koruyoruz.</p>',
            '<p><strong>Uygun fiyat mezar yapımı</strong> sunarken kaliteden asla ödün vermeyiz. <em>Karaca Ahmet, Zincirlikuyu, Eyüp Sultan, Edirnekapı</em> mezarlıklarında gerçekleştirdiğimiz tüm projelerimiz <strong>5 yıl işçilik garantisi</strong> ile teslim edilir. <em>Modern mezar tasarımı, klasik mezar modelleri</em> ve özel tasarım projelerimizde <strong>mükemmellik standardı</strong> hedefliyoruz.</p>',
          '</div>',
        '</div>',
        '<div class="bg-white border border-gray-200 p-8 rounded-xl shadow-lg mb-8">',
          '<h2 class="text-xl text-blue-600 mb-6 flex itemsarker">',
            '<span class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center mr-3 text-white text-sm">🔍</span>',
            'Mezar Yapım Kalite Kontrol Sürecimiz',
          '</h2>',
          '<div class="grid md:grid-cols-2 gap-6">',
            '<div class="space-y-4">',
              '<div class="flex items-start"><span class="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1">1</span><div><h3 class="text-sm text-gray-900 mb-1">Malzeme Kalite Kontrolü</h3><p class="text-xs text-gray-600"><strong>A+ sınıf mermer ve granit</strong> seçimi, dayanıklılık testleri</p></div></div>',
              '<div class="flex items-start"><span class="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1">2</span><div><h3 class="text-sm text-gray-900 mb-1">Ölçüm ve Planlama</h3><p class="text-xs text-gray-600"><strong>Ücretsiz keşif</strong>, teknik çizim ve <em>İBB standartları</em> kontrolü</p></div></div>',
              '<div class="flex items-start"><span class="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1">3</span><div><h3 class="text-sm text-gray-900 mb-1">İşçilik Kalitesi</h3><p class="text-xs text-gray-600"><strong>25+ yıl deneyimli ustalar</strong>, profesyonel araç-gereç kullanımı</p></div></div>',
            '</div>',
            '<div class="space-y-4">',
              '<div class="flex items-start"><span class="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1">4</span><div><h3 class="text-sm text-gray-900 mb-1">Montaj ve Uygulama</h3><p class="text-xs text-gray-600"><strong>Hassas montaj</strong>, estetik detaylar ve <em>dayanıklılık</em> odaklı kurulum</p></div></div>',
              '<div class="flex items-start"><span class="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1">5</span><div><h3 class="text-sm text-gray-900 mb-1">Final Kontrolü</h3><p class="text-xs text-gray-600"><strong>Teslim öncesi kalite</strong> kontrolü, <em>müşteri memnuniyet</em> onayı</p></div></div>',
              '<div class="flex items-start"><span class="w-6 h-6 bg-purple-500 rounded-full flex items-center justify-center mr-3 text-white text-xs mt-1">6</span><div><h3 class="text-sm text-gray-900 mb-1">Garanti ve Takip</h3><p class="text-xs text-gray-600"><strong>5 yıl garanti</strong>, ücretsiz bakım kontrolü ve <em>7/24 destek</em></p></div></div>',
            '</div>',
          '</div>',
        '</div>',
        '<div class="bg-gradient-to-br from-gray-50 to-gray-100 p-8 rounded-xl shadow-lg mb-8">',
          '<h2 class="text-xl text-teal-600 mb-6 flex items-center">',
            '<span class="w-8 h-8 bg-teal-500 rounded-full flex items-center justify-center mr-3 text-white text-sm">📋</span>',
            'İstanbul Mezar Yapımında Kalite İlkelerimiz',
          '</h2>',
          '<div class="grid md:grid-cols-2 gap-4">',
            '<div class="space-y-4">',
              '<div class="flex items-start bg-white p-4 rounded-lg shadow-sm"><span class="w-4 h-4 bg-gradient-to-r from-teal-500 to-teal-600 rounded-full mt-1 mr-3 flex-shrink-0"></span><div><h3 class="text-sm text-gray-900 mb-1">Müşteri Memnuniyeti Garantisi</h3><p class="text-xs text-gray-600"><strong>%98 müşteri memnuniyeti</strong> oranı ile <em>mezar yapımında</em> güvenilir hizmet</p></div></div>',
              '<div class="flex items-start bg-white p-4 rounded-lg shadow-sm"><span class="w-4 h-4 bg-gradient-to-r from-blue-500 to-blue-600 rounded-full mt-1 mr-3 flex-shrink-0"></span><div><h3 class="text-sm text-gray-900 mb-1">A+ Kalite Malzeme Kullanımı</h3><p class="text-xs text-gray-600"><strong>Mermer, granit, traverten</strong> seçiminde <em>kaliteden taviz yok</em></p></div></div>',
              '<div class="flex items-start bg-white p-4 rounded-lg shadow-sm"><span class="w-4 h-4 bg-gradient-to-r from-green-500 to-green-600 rounded-full mt-1 mr-3 flex-shrink-0"></span><div><h3 class="text-sm text-gray-900 mb-1">Zamanında Teslimat Garantisi</h3><p class="text-xs text-gray-600"><strong>%95 zamanında teslimat</strong> oranı, <em>söz verdiğimiz tarihte</em> teslim</p></div></div>',
            '</div>',
            '<div class="space-y-4">',
              '<div class="flex items-start bg-white p-4 rounded-lg shadow-sm"><span class="w-4 h-4 bg-gradient-to-r from-purple-500 to-purple-600 rounded-full mt-1 mr-3 flex-shrink-0"></span><div><h3 class="text-sm text-gray-900 mb-1">Sürekli Gelişim ve İnovasyon</h3><p class="text-xs text-gray-600"><strong>Modern mezar tasarımları</strong> ve <em>teknolojik yenilikler</em> takibi</p></div></div>',
              '<div class="flex items-start bg-white p-4 rounded-lg shadow-sm"><span class="w-4 h-4 bg-gradient-to-r from-orange-500 to-orange-600 rounded-full mt-1 mr-3 flex-shrink-0"></span><div><h3 class="text-sm text-gray-900 mb-1">Çevre Dostu Mezar Yapımı</h3><p class="text-xs text-gray-600"><strong>Sürdürülebilir malzeme</strong> kullanımı ve <em>doğa dostu</em> üretim</p></div></div>',
              '<div class="flex items-start bg-white p-4 rounded-lg shadow-sm"><span class="w-4 h-4 bg-gradient-to-r from-red-500 to-red-600 rounded-full mt-1 mr-3 flex-shrink-0"></span><div><h3 class="text-sm text-gray-900 mb-1">Profesyonel Ekip Çalışması</h3><p class="text-xs text-gray-600"><strong>25+ yıl deneyimli ustalar</strong>, <em>takım halinde</em> mükemmel sonuç</p></div></div>',
            '</div>',
          '</div>',
        '</div>',
        '<div class="bg-gradient-to-r from-teal-500 to-blue-500 text-white p-8 rounded-xl shadow-lg">',
          '<div class="flex items-center mb-4">',
            '<span class="w-12 h-12 bg-white bg-opacity-20 rounded-full flex items-center justify-center mr-4 text-2xl">🤝</span>',
            '<h2 class="text-xl m-0">Kalite Taahhüdümüz</h2>',
          '</div>',
          '<div class="space-y-4 text-white/95">',
            '<p><strong>İstanbul\'da mezar yapımı konusunda sektör lideri</strong> olarak, <em>kalite standartlarımızı sürekli yükseltmeyi</em>, müşterilerimizin beklentilerini karşılamayı ve aşmayı taahhüt ediyoruz. <strong>Her mezar projemizde mükemmellik</strong> arayışımız devam etmektedir.</p>',
            '<p><em>Tek kişilik mezar, iki kişilik mezar, aile mezarı</em> ve özel tasarım projelerimizde <strong>5 yıl işçilik garantisi</strong> veriyor, <em>ücretsiz bakım kontrolü</em> ile hizmetimizi sürdürüyoruz. <strong>Mezarlarınızın kalitesi bizim gururumuzdur</strong>.</p>',
          '</div>',
          '<div class="grid grid-cols-3 gap-4 mt-6 pt-6 border-t border-white/30">',
            '<div class="text-center"><div class="text-2xl mb-1">98%</div><div class="text-xs opacity-90">Müşteri Memnuniyeti</div></div>',
            '<div class="text-center"><div class="text-2xl mb-1">5 Yıl</div><div class="text-xs opacity-90">İşçilik Garantisi</div></div>',
            '<div class="text-center"><div class="text-2xl mb-1">25+</div><div class="text-xs opacity-90">Yıl Deneyim</div></div>',
          '</div>',
        '</div>',
      '</section>'
    )
  ),
  'https://res.cloudinary.com/dbozv7wqd/image/upload/v1762878680/custom_pages/609da17f-bee8-11f0-947f-e7685059cf04/cover/mezartasi.png', NULL, NULL,
  'Kalite Politikamız - Mezarisim.com | İstanbul Mezar Yapımı',
  'A+ malzeme, 5 yıl işçilik garantisi ve %98 müşteri memnuniyeti ile İstanbul mezar yapımı kalite politikamız.',
  1,
  NOW(3), NOW(3)
),
-- RAMAZAN KAMPANYASI (✅ alt NULL eklendi; sütun sayısı 12 oldu)
(
  UUID(),
  'Ramazan Ayı Özel İndirim Kampanyası',
  'ramazan-kampanyasi',
  JSON_OBJECT('html', CONCAT(
    '<div class="min-h-screen bg-gray-50 py-8">',
    '  <div class="container mx-auto px-4 max-w-4xl">',
    '    <a href="/" class="inline-flex items-center gap-2 mb-6 border border-teal-500 text-teal-600 rounded-md px-3 py-2 hover:bg-teal-50 transition">&#8592; Ana Sayfaya Dön</a>',
    '    <article class="bg-white rounded-lg shadow-lg overflow-hidden">',
    '      <div class="relative h-64 md:h-80">',
    '        <img src="https://images.unsplash.com/photo-1594968973184-9040a5a79963?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaXNjb3VudCUyMHNhbGUlMjBwZXJjZW50YWdlfGVufDF8fHx8MTc1NjA3MTEzNnww&amp;ixlib=rb-4.1.0&amp;q=80&amp;w=800&amp;h=400&amp;fit=crop&amp;crop=center" alt="Ramazan Ayı Özel İndirim Kampanyası" class="w-full h-full object-cover" />',
    '        <div class="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"></div>',
    '        <div class="absolute bottom-4 left-4 text-white"><span class="bg-teal-500 px-3 py-1 rounded-full text-sm font-semibold">Kampanya</span></div>',
    '      </div>',
    '      <div class="p-6 md:p-8">',
    '        <div class="flex items-center gap-4 mb-6 text-sm text-gray-600">',
    '          <div class="flex items-center gap-2"><span>📅</span><span>Mart 2024</span></div>',
    '          <div class="flex items-center gap-2"><span>🏷️</span><span>Kampanya</span></div>',
    '        </div>',
    '        <h1 class="text-3xl md:text-4xl font-bold text-gray-800 mb-6">Ramazan Ayı Özel İndirim Kampanyası</h1>',
    '        <div class="prose max-w-none space-y-6">',
    '          <div class="bg-teal-50 border-l-4 border-teal-500 p-6 rounded">',
    '            <h2 class="text-xl font-semibold text-teal-700 mb-3">🌙 Ramazan Ayı Boyunca %20 İndirim Fırsatı!</h2>',
    '            <p class="text-gray-700 leading-relaxed">Bu mübarek Ramazan ayında, tüm mezar yapım hizmetlerimizde özel indirim kampanyamız başladı. Mermer ve granit mezar modelleri, mezar baş taşları ve tüm yapım hizmetlerinde geçerli olan bu kampanya sınırlı sürelidir.</p>',
    '          </div>',
    '          <div class="grid md:grid-cols-2 gap-6">',
    '            <div class="bg-white border border-gray-200 p-6 rounded-lg">',
    '              <h3 class="text-lg font-semibold text-gray-800 mb-4">Kampanya Kapsamı</h3>',
    '              <ul class="space-y-2 text-gray-700">',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-teal-500 rounded-full"></span>Tek kişilik mermer mezar modelleri</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-teal-500 rounded-full"></span>İki kişilik mermer mezar modelleri</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-teal-500 rounded-full"></span>Granit mezar modelleri</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-teal-500 rounded-full"></span>Mezar baş taşları</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-teal-500 rounded-full"></span>İşçilik ve montaj hizmetleri</li>',
    '              </ul>',
    '            </div>',
    '            <div class="bg-white border border-gray-200 p-6 rounded-lg">',
    '              <h3 class="text-lg font-semibold text-gray-800 mb-4">Kampanya Şartları</h3>',
    '              <ul class="space-y-2 text-gray-700">',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-orange-500 rounded-full"></span>Kampanya Ramazan ayı boyunca geçerlidir</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-orange-500 rounded-full"></span>Peşin ödemede geçerlidir</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-orange-500 rounded-full"></span>Diğer kampanyalarla birleştirilemez</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-orange-500 rounded-full"></span>Minimum 5.000 TL tutarında siparişlerde geçerli</li>',
    '                <li class="flex items-center gap-2"><span class="w-2 h-2 bg-orange-500 rounded-full"></span>Sözleşme imzalanması gerekir</li>',
    '              </ul>',
    '            </div>',
    '          </div>',
    '          <div class="bg-gray-100 p-6 rounded-lg">',
    '            <h3 class="text-xl font-semibold text-gray-800 mb-4">🕐 Kampanya Süresi</h3>',
    '            <p class="text-gray-700 leading-relaxed mb-4">Bu özel kampanya <strong>Ramazan ayı başlangıcından itibaren ay sonuna kadar</strong> geçerlidir. Bu fırsatı kaçırmamak için hemen bizimle iletişime geçin ve ücretsiz keşif hizmetinden yararlanın.</p>',
    '            <div class="flex flex-col sm:flex-row gap-3">',
    '              <a href="tel:+905334838971" class="inline-flex items-center justify-center bg-teal-500 hover:bg-teal-600 text-white px-4 py-2 rounded-md">Hemen Ara: 0533 483 89 71</a>',
    '              <a href="https://wa.me/905334838971?text=Ramazan%20kampanyası%20hakkında%20bilgi%20almak%20istiyorum" class="inline-flex items-center justify-center border border-teal-500 text-teal-600 hover:bg-teal-50 px-4 py-2 rounded-md">WhatsApp ile İletişim</a>',
    '            </div>',
    '          </div>',
    '          <div class="bg-yellow-50 border border-yellow-200 p-6 rounded-lg">',
    '            <h3 class="text-lg font-semibold text-yellow-800 mb-3">⚠️ Önemli Uyarı</h3>',
    '            <p class="text-yellow-700 leading-relaxed">Kampanya kapsamında verilen indirimler sadece Ramazan ayı boyunca geçerlidir. Ay sonundan sonra yapılacak başvurular normal fiyatlandırma ile değerlendirilecektir. Detaylı bilgi ve fiyat teklifi için lütfen bizimle iletişime geçin.</p>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </article>',
    '    <div class="mt-8 grid md:grid-cols-3 gap-4">',
    '      <a href="/models" class="block h-auto p-4 border border-teal-500 text-teal-600 rounded-md hover:bg-teal-50"><h4 class="font-semibold mb-1">Mezar Modelleri</h4><p class="text-sm text-gray-600">Tüm mezar modellerimizi inceleyin</p></a>',
    '      <a href="/pricing" class="block h-auto p-4 border border-teal-500 text-teal-600 rounded-md hover:bg-teal-50"><h4 class="font-semibold mb-1">Fiyat Listesi</h4><p class="text-sm text-gray-600">Güncel fiyatları görüntüleyin</p></a>',
    '      <a href="/contact" class="block h-auto p-4 border border-teal-500 text-teal-600 rounded-md hover:bg-teal-50"><h4 class="font-semibold mb-1">İletişim</h4><p class="text-sm text-gray-600">Bizimle iletişime geçin</p></a>',
    '    </div>',
    '  </div>',
    '</div>'
  )),
  'https://images.unsplash.com/photo-1594968973184-9040a5a79963?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaXNjb3VudCUyMHNhbGUlMjBwZXJjZW50YWdlfGVufDF8fHx8MTc1NjA3MTEzNnww&ixlib=rb-4.1.0&q=80&w=800&h=400&fit=crop&crop=center',
  NULL,              -- storage_asset_id
  NULL,              -- ✅ alt (eksikti)
  'Ramazan Ayı Özel İndirim Kampanyası',
  'Ramazan boyunca mezar yapım hizmetlerinde %20 indirim. Mermer/granit mezar, baş taşı, işçilik ve montajda fırsatlar. İstanbul geneli ücretsiz keşif.',
  1,
  NOW(3), NOW(3)
)
ON DUPLICATE KEY UPDATE
  `title`            = VALUES(`title`),
  `content`          = VALUES(`content`),
  `image_url`        = VALUES(`image_url`),
  `storage_asset_id` = VALUES(`storage_asset_id`),
  `alt`              = VALUES(`alt`),
  `meta_title`       = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `is_published`     = VALUES(`is_published`),
  `updated_at`       = VALUES(`updated_at`);
